In [1]:
import torch

print(torch.__version__)

2.8.0+cpu


In [2]:
x = torch.tensor([1,2,3])

print(x)

print(type(x))

tensor([1, 2, 3])
<class 'torch.Tensor'>


In [3]:
matrix = torch.tensor([
    [1,2],
    [3,4]
])

matrix

tensor([[1, 2],
        [3, 4]])

In [4]:
print(matrix.shape)

torch.Size([2, 2])


In [5]:
random_tensor = torch.rand(3,4)

random_tensor

tensor([[0.4730, 0.0626, 0.8619, 0.6542],
        [0.0418, 0.8822, 0.4942, 0.9942],
        [0.7358, 0.2108, 0.2782, 0.3813]])

In [6]:
torch.zeros(4,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [7]:
torch.ones(4,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [8]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [9]:
a = torch.tensor([1,2,3])

b = torch.tensor([4,5,6])

print(a+b)

print(a*b)

tensor([5, 7, 9])
tensor([ 4, 10, 18])


In [10]:
print(torch.cuda.is_available())

False


In [11]:
weights = torch.rand(3)

input_data = torch.tensor([2.,4.,6.])

prediction = weights * input_data

prediction

tensor([1.4738, 0.3133, 0.5173])